---
platform: linux

inputs:
  - name: task_output

image_resource:
  type: docker-image
  source: {repository: particle/buildpack-particle-firmware}

run:
  path: cat
  args:
    - task_output/hello_world.txt
