resources:
  - name: concourse-repo
    type: git
    source:
      uri: https://github.com/XuGuohui/concourse.git
      branch: master

jobs:
  - name: run-task-with-inputs
    public: true
    plan:
      - get: concourse-repo
        trigger: true
      - task: hello-world
        file: concourse-repo/tasks/hello_world.yml
